-- Give definitions of the lists of Fibonacci numbers [0,1,1,2,3,5, .....] and Hamming numbers
-- [1,2,3,4,5,6,8,9,...] (defined on page 447) using networks of processes.
-- For the latter problem, you may find the merge function of the previous question useful.
